### ISSUE TITLE
[Question] How to setup the dev environment

### ISSUE THREAD

**Issue by BonfaceKilz** [ryanprior/lutrine-dice#1]
I followed the instructions in the README: `docker-compose up -d` and I get the following trace:

```
Creating network "lutrine-dice_default" with the default driver
Pulling server (crystallang/crystal:1.0.0-alpine)...
1.0.0-alpine: Pulling from crystallang/crystal
f84cab65f19f: Pull complete
e3964af52a87: Pull complete
0f77b10f9f82: Pull complete
c33693e84d2b: Pull complete
aa64e91ee860: Pull complete
Digest: sha256:c9b59f80f6b3821596f45494cd56c3b08048067e18ff0b12c26888830fe167d6
Status: Downloaded newer image for crystallang/crystal:1.0.0-alpine
Pulling client (mint:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y     
Pulling client (mint:)...
ERROR: pull access denied for mint, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Anything weird I'm doing? I'll try troubleshooting this later; but any help in the meantime is welcome!

**Comment by ryanprior** [comment]
Hi @BonfaceKilz, thanks for the question!

The answer is kinda ugly. I have a local image tagged `mint` I built myself with the Mint 1.2 compiler in it. The `mintlang/mint` image from Dockerhub has the 1.3-dev release, which I ran into issues with due to breaking syntax changes.

So there's at least three ways to fix it:
1) use the `ryanprior/mint` image from DockerHub, which has my 1.2 image in there
2) update the mint-lang build infrastructure to push version tags, so we can use a specific tag like `mintlang/mint:0.2`
3) figure out how to fix our syntax to work with the changes in the 1.3 compiler

Eventually solution 3 is the only sustainable one. The others just kicks the can down the road 'til we find something that forces an upgrade.

**Comment by ryanprior** [comment]
This should be fixed for now @BonfaceKilz, I've updated the project to use the latest Mint container from DockerHub and it wasn't as much work as I feared. (Ten minutes once I got some tips from the Mint gitter.)

**Comment by BonfaceKilz** [comment]
Ryan Prior ***@***.***> anaandika:

> This should be fixed for now @BonfaceKilz, I've
> updated the project to use the latest Mint
> container from DockerHub and it wasn't as much
> work as I feared. (Ten minutes once I got some
> tips from the Mint gitter.)

Thanks dude! Looking forward to hacking this. I'll
try out tomorrow at night my time(EAT) and let you
know if I run into any problems.

-- 
Bonface M. K. D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
Free Software Activist
Humble GNU Emacs User | Bearer of scheme-y parens
Curator: <https://upbookclub.com> | Twitter: @BonfaceKilz
